---

name: Lint Commit message

on:
  push:
  pull_request:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: https://raw.githubusercontent.com/projectpotos/.github/main/.github/configs/commitlint.config.js
