---

name: Lint Commit message

on:
  push:
  pull_request:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          mkdir -p ${GITHUB_WORKSPACE}/.github/configs
          cat <<EOF > ${GITHUB_WORKSPACE}/.github/configs/commitlint.config.js
          module.exports = {
            rules: {
              'body-max-line-length': [0, "always"],
            },
          }
          EOF
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ${GITHUB_WORKSPACE}/.github/configs/commitlint.config.js
